name: hansa_lab
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.37+72

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter


  cupertino_icons: ^1.0.2
  google_fonts: ^4.0.3
  flutter_spinkit: ^5.1.0
  flutter_screenutil: ^5.6.0
  flip_card: ^0.7.0
  provider: ^6.0.5
  sticky_headers: ^0.3.0+2
  chewie: ^1.3.6
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  syncfusion_flutter_datepicker: ^22.1.39
  url_launcher: ^6.1.8
  cached_network_image: ^3.2.3
  dio: ^4.0.6
  path_provider: ^2.0.10
  flutter_html:
  rename: ^2.1.1
  percent_indicator: ^4.2.2
  lottie: ^2.2.0
  intl_phone_number_input: ^0.7.0+2
  share_plus: ^4.0.10+1
  permission_handler: ^10.2.0
  firebase_core: ^2.7.0
  firebase_messaging: ^14.2.5
  firebase_crashlytics: ^3.1.0
  gallery_saver: ^2.1.1
  flutter_local_notifications: ^12.0.4
  syncfusion_flutter_pdfviewer: ^22.1.34
#  firebase_notifications_handler: ^1.1.0
  move_to_background: ^1.0.2
  flutter_rating_bar: ^4.0.1
  top_snackbar_flutter: ^2.1.1
  image_picker: ^0.8.5+3
  mask_text_input_formatter: ^2.4.0
  open_filex:
  sentry_flutter:
#  tap_debouncer: ^2.2.0
  keyboard_dismisser: ^3.0.0
  device_information: ^0.0.4
  flutter_app_badger: ^1.5.0
  flutter_keychain: ^2.2.1
  gradient_borders: 1.0.0
  flutter_svg: ^1.1.6
  flutter_widget_from_html:
  firebase_dynamic_links: ^5.0.16
  uni_links: ^0.5.1
  qr_code_scanner: ^1.0.1
  package_info_plus:
  firebase_remote_config: ^3.0.15

dependency_overrides:
  http: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.9.2"
  flutter_lints: ^2.0.1
  
flutter_icons:
  android: true
  ios: true
  image_path: "assets/192.png"
  
  

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true
  assets:
    - assets/
    - assets/quizz.png
    - assets/ssss.png
    - assets/bigquiz.png
    - assets/bigquizz.png
